# Generated by Django 6.0.1 on 2026-01-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_user_is_approved_user_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='accounts.managerprofile')),
            ],
            options={
                'unique_together': {('manager', 'date')},
            },
        ),
    ]
