# Generated by Django 6.0.1 on 2026-01-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_amount_payment_booking_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manager_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('RELEASED', 'Released')], default='PENDING', max_length=20),
        ),
    ]
