# Generated by Django 6.0.1 on 2026-01-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0008_rename_event_date_event_date_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CHECKED_IN', 'Checked In')], default='REGISTERED', max_length=15)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
