# Generated by Django 6.0.1 on 2026-01-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='EventTemplate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='EventMedia',
        ),
    ]
