# Generated by Django 6.0.1 on 2026-03-26 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CREATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'status', 'start_date'], name='idx_event_public_search'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_event_user_dashboard'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'end_date'], name='idx_event_status_autoclose'),
        ),
    ]
