# Generated by Django 6.0.1 on 2026-01-20 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventmedia_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='event_type',
            field=models.CharField(choices=[('WEDDING', 'Wedding'), ('BIRTHDAY', 'Birthday'), ('CORPORATE', 'Corporate'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
