# Generated by Django 6.0.1 on 2026-02-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_contact_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtemplate',
            name='pdf_content',
            field=models.TextField(blank=True, default='', help_text='Table-based HTML for PDF generation'),
        ),
    ]
