# Generated by Django 6.0.1 on 2026-02-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_invitationtemplate_pdf_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationtemplate',
            name='pdf_content',
        ),
    ]
