# Generated by Django 6.0.1 on 2026-01-20 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_servicepackage_created_at_servicepackage_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='event_type',
            field=models.CharField(choices=[('WEDDING', 'Wedding'), ('BIRTHDAY', 'Birthday'), ('CORPORATE', 'Corporate'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
