# Generated by Django 6.0.1 on 2026-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_user_event_created_by_event_pricing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiceventregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publiceventregistration',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publiceventregistration',
            name='payment_status',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('PENDING', 'Pending')], default='FREE', max_length=20),
        ),
    ]
