# Generated by Django 6.0.1 on 2026-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_publiceventregistration_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiceventregistration',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publiceventregistration',
            name='payment_status',
            field=models.CharField(choices=[('FREE', 'Free'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='FREE', max_length=10),
        ),
    ]
