# Generated by Django 6.0.1 on 2026-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_publiceventregistration_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiceventregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
