# Generated by Django 6.0.1 on 2026-02-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_publiceventregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
