# Generated by Django 6.0.1 on 2026-01-31 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0002_remove_manageravailability_bookings_ma_manager_ca7077_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageravailability',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='manageravailability',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked (Event)'), ('BLOCKED', 'Blocked (Manual)')], default='BLOCKED', max_length=20),
        ),
    ]
