# Generated by Django 6.0.1 on 2026-01-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('OTP_SENT', 'OTP Sent'), ('OTP_FAILED', 'OTP Failed'), ('PASSWORD_RESET', 'Password Reset'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected')], max_length=50),
        ),
    ]
