# Generated by Django 6.0.1 on 2026-03-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog_admin_alter_managerprofile_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
