# Generated by Django 6.0.1 on 2026-01-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='manageravailability',
            name='bookings_ma_manager_ca7077_idx',
        ),
        migrations.DeleteModel(
            name='ManagerAvailability',
        ),
    ]
