# Generated by Django 6.0.1 on 2026-01-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
